//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacultyEntities : DbContext
    {
        public FacultyEntities()
            : base("name=FacultyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProgramSubjectsSet> ProgramSubjectsSets { get; set; }
        public DbSet<StudyProgramSet> StudyProgramSets { get; set; }
        public DbSet<StudySubjectSet> StudySubjectSets { get; set; }
        public DbSet<TeacherSet> TeacherSets { get; set; }
        public DbSet<UserSet> UserSets { get; set; }
    }
}
