//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSubjectsSet
    {
        public int Id { get; set; }
        public Nullable<int> StudySubject_Id { get; set; }
        public Nullable<int> StudyProgram_Id { get; set; }
    
        public virtual StudyProgramSet StudyProgramSet { get; set; }
        public virtual StudySubjectSet StudySubjectSet { get; set; }
    }
}
