//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudySubjectSet
    {
        public StudySubjectSet()
        {
            this.ProgramSubjectsSets =
                new HashSet<ProgramSubjectsSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AutumOrSpring { get; set; }
        public string Form { get; set; }
        public int Teacher_Id { get; set; }
    
        public virtual ICollection<ProgramSubjectsSet> 
            ProgramSubjectsSets { get; set; }
        public virtual TeacherSet TeacherSet { get; set; }
    }
}
