//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSet
    {
        public TeacherSet()
        {
            this.StudySubjectSets = new HashSet<StudySubjectSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MidleName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
    
        public virtual ICollection<StudySubjectSet>
            StudySubjectSets { get; set; }
    }
}
