
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.xml.bind.DatatypeConverter;


public class GUI extends javax.swing.JFrame {
    
    private RM rm;
    private CPU cpu;
    
    
    public GUI(RM rm) {
        this.rm = rm;
        cpu = rm.getCPU();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pcTextField = new javax.swing.JTextField();
        pcLabel = new javax.swing.JLabel();
        ptrLabel = new javax.swing.JLabel();
        ptrTextField = new javax.swing.JTextField();
        spLabel = new javax.swing.JLabel();
        spTextField = new javax.swing.JTextField();
        tiLabel = new javax.swing.JLabel();
        tiTextField = new javax.swing.JTextField();
        modeTextField = new javax.swing.JTextField();
        modeLabel = new javax.swing.JLabel();
        siLabel = new javax.swing.JLabel();
        siTextField = new javax.swing.JTextField();
        piLabel = new javax.swing.JLabel();
        piTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoryTextArea = new javax.swing.JTextArea();
        memoryLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nextStepButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        externalMemoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OS");

        pcTextField.setEditable(false);

        pcLabel.setText("PC");

        ptrLabel.setText("PTR");

        ptrTextField.setEditable(false);

        spLabel.setText("SP");

        spTextField.setEditable(false);

        tiLabel.setText("TI");

        tiTextField.setEditable(false);

        modeTextField.setEditable(false);

        modeLabel.setText("MODE");

        siLabel.setText("SI");

        siTextField.setEditable(false);

        piLabel.setText("PI");

        piTextField.setEditable(false);

        memoryTextArea.setEditable(false);
        memoryTextArea.setColumns(20);
        memoryTextArea.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        memoryTextArea.setRows(5);
        jScrollPane1.setViewportView(memoryTextArea);

        memoryLabel.setText("Memory");

        jLabel2.setText("CPU Registers");

        nextStepButton.setText("Next step");
        nextStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        externalMemoryButton.setText("Update External Memory");
        externalMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalMemoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modeTextField)
                                    .addComponent(pcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ptrLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(siLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(piLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ptrTextField)
                                    .addComponent(spTextField)
                                    .addComponent(tiTextField)
                                    .addComponent(siTextField)
                                    .addComponent(piTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(memoryLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextStepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(externalMemoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {modeTextField, pcTextField, piTextField, ptrTextField, siTextField, spTextField, tiTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memoryLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptrLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiLabel)
                            .addComponent(tiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siLabel)
                            .addComponent(siTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piLabel))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextStepButton)
                    .addComponent(updateButton)
                    .addComponent(externalMemoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {modeLabel, modeTextField, pcLabel, pcTextField, piTextField, ptrLabel, ptrTextField, siTextField, spLabel, spTextField, tiLabel, tiTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        StringBuilder sb = new StringBuilder();
        Word[] data = rm.viewRealMemory();
        for(int i = 0; i < data.length; i++){
            if(i % 4 == 0){
                sb.append("\n");
                sb.append(Integer.toHexString(i * 4));
                sb.append("\t");
            }
            sb.append(DatatypeConverter.printHexBinary(data[i].getBytes()));
            sb.append(" ");
            
        }
        memoryTextArea.setText(sb.toString());
    }//GEN-LAST:event_updateButtonActionPerformed

    private void nextStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStepButtonActionPerformed
        synchronized(rm){
            if(rm.nextStep() == 1){
                rm.notify();
            }
            updateRegisters();
        }
    }//GEN-LAST:event_nextStepButtonActionPerformed

    private void externalMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalMemoryButtonActionPerformed
        // TODO add your handling code here:
            Word[] externalMemory = rm.viewExternalMemory();     
            FileOutputStream out = null;
            try {
                out = new FileOutputStream(new File("externalMemory.bin"));
            for (Word data : externalMemory) {
                out.write(data.getBytes());
            }
            out.close();
            //System.out.println("External memory saved in file: externalMemory.bin");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally {
                try {
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
    }//GEN-LAST:event_externalMemoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void setStepButtonEnabled(boolean value){
        nextStepButton.setEnabled(value);
    }
    
    public void updateRegisters() {
        pcTextField.setText(Integer.toString(cpu.getPC()));
        piTextField.setText(Integer.toString(cpu.getPI()));
        ptrTextField.setText(Integer.toString(cpu.getPTR()));
        siTextField.setText(Integer.toString(cpu.getSI()));
        tiTextField.setText(Integer.toString(cpu.getTI()));
        spTextField.setText(Integer.toString(cpu.getSP()));
        modeTextField.setText(Integer.toString(cpu.getMODE()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton externalMemoryButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel memoryLabel;
    private javax.swing.JTextArea memoryTextArea;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JTextField modeTextField;
    private javax.swing.JButton nextStepButton;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JTextField pcTextField;
    private javax.swing.JLabel piLabel;
    private javax.swing.JTextField piTextField;
    private javax.swing.JLabel ptrLabel;
    private javax.swing.JTextField ptrTextField;
    private javax.swing.JLabel siLabel;
    private javax.swing.JTextField siTextField;
    private javax.swing.JLabel spLabel;
    private javax.swing.JTextField spTextField;
    private javax.swing.JLabel tiLabel;
    private javax.swing.JTextField tiTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
