//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionic.Samples.Webservices.Sep24
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationTask", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class LocationTask : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DatabaseIdField;
        
        private string InfoField;
        
        private string LabelField;
        
        private System.DateTime LastTimeModifiedField;
        
        private Ionic.Samples.Webservices.Sep24.Location LocationField;
        
        private string NameField;
        
        private string StatusField;
        
        private string UserEmailField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatabaseId
        {
            get
            {
                return this.DatabaseIdField;
            }
            set
            {
                this.DatabaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTimeModified
        {
            get
            {
                return this.LastTimeModifiedField;
            }
            set
            {
                this.LastTimeModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ionic.Samples.Webservices.Sep24.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                this.UserEmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private double LatitudeField;
        
        private double LongtitudeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude
        {
            get
            {
                return this.LongtitudeField;
            }
            set
            {
                this.LongtitudeField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Location.MeasurementSystem", Namespace="http://schemas.datacontract.org/2004/07/")]
        public enum MeasurementSystem : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Imperial = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Metric = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DatabaseIdField;
        
        private string EmailField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string SurnameField;
        
        private string UserLevelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatabaseId
        {
            get
            {
                return this.DatabaseIdField;
            }
            set
            {
                this.DatabaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLevel
        {
            get
            {
                return this.UserLevelField;
            }
            set
            {
                this.UserLevelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Schema.Lukas.Somee.com", ConfigurationName="Ionic.Samples.Webservices.Sep24.ILocationBasedTasksService")]
    public interface ILocationBasedTasksService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTaskResponse")]
        int AddTask(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTaskResponse")]
        System.Threading.Tasks.Task<int> AddTaskAsync(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistance", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistanceResponse")]
        double GetDistance(Ionic.Samples.Webservices.Sep24.Location obj1, Ionic.Samples.Webservices.Sep24.Location obj2, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistance", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistanceResponse")]
        System.Threading.Tasks.Task<double> GetDistanceAsync(Ionic.Samples.Webservices.Sep24.Location obj1, Ionic.Samples.Webservices.Sep24.Location obj2, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasks", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasksResponse")]
        Ionic.Samples.Webservices.Sep24.LocationTask[] FindNearTasks(Ionic.Samples.Webservices.Sep24.Location center, int radius, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasks", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasksResponse")]
        System.Threading.Tasks.Task<Ionic.Samples.Webservices.Sep24.LocationTask[]> FindNearTasksAsync(Ionic.Samples.Webservices.Sep24.Location center, int radius, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTaskResponse")]
        bool DeleteTask(int taskId, Ionic.Samples.Webservices.Sep24.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTaskResponse")]
        System.Threading.Tasks.Task<bool> DeleteTaskAsync(int taskId, Ionic.Samples.Webservices.Sep24.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/UpdateTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/UpdateTaskResponse")]
        bool UpdateTask(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/UpdateTask", ReplyAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/UpdateTaskResponse")]
        System.Threading.Tasks.Task<bool> UpdateTaskAsync(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationBasedTasksServiceChannel : Ionic.Samples.Webservices.Sep24.ILocationBasedTasksService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationBasedTasksServiceClient : System.ServiceModel.ClientBase<Ionic.Samples.Webservices.Sep24.ILocationBasedTasksService>, Ionic.Samples.Webservices.Sep24.ILocationBasedTasksService
    {
        
        public LocationBasedTasksServiceClient()
        {
        }
        
        public LocationBasedTasksServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LocationBasedTasksServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocationBasedTasksServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LocationBasedTasksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int AddTask(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.AddTask(task, user);
        }
        
        public System.Threading.Tasks.Task<int> AddTaskAsync(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.AddTaskAsync(task, user);
        }
        
        public double GetDistance(Ionic.Samples.Webservices.Sep24.Location obj1, Ionic.Samples.Webservices.Sep24.Location obj2, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system)
        {
            return base.Channel.GetDistance(obj1, obj2, system);
        }
        
        public System.Threading.Tasks.Task<double> GetDistanceAsync(Ionic.Samples.Webservices.Sep24.Location obj1, Ionic.Samples.Webservices.Sep24.Location obj2, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system)
        {
            return base.Channel.GetDistanceAsync(obj1, obj2, system);
        }
        
        public Ionic.Samples.Webservices.Sep24.LocationTask[] FindNearTasks(Ionic.Samples.Webservices.Sep24.Location center, int radius, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system)
        {
            return base.Channel.FindNearTasks(center, radius, system);
        }
        
        public System.Threading.Tasks.Task<Ionic.Samples.Webservices.Sep24.LocationTask[]> FindNearTasksAsync(Ionic.Samples.Webservices.Sep24.Location center, int radius, Ionic.Samples.Webservices.Sep24.Location.MeasurementSystem system)
        {
            return base.Channel.FindNearTasksAsync(center, radius, system);
        }
        
        public bool DeleteTask(int taskId, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.DeleteTask(taskId, user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTaskAsync(int taskId, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.DeleteTaskAsync(taskId, user);
        }
        
        public bool UpdateTask(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.UpdateTask(task, user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTaskAsync(Ionic.Samples.Webservices.Sep24.LocationTask task, Ionic.Samples.Webservices.Sep24.User user)
        {
            return base.Channel.UpdateTaskAsync(task, user);
        }
    }
}
