<?xml version="1.0" encoding="utf-8"?>
<!--Created with Liquid XML 2014 Designer Edition (Trial) 12.1.5.5062 (http://www.liquid-technologies.com)-->
<wsdl:definitions name="LocationBasedTasksService"
                  targetNamespace="http://Schema.Lukas.Somee.com"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:tns="http://Schema.Lukas.Somee.com"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:i0="http://tempuri.org/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified"
                   targetNamespace="http://Schema.Lukas.Somee.com"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:import schemaLocation="wsdl://2"
                       namespace="http://schemas.datacontract.org/2004/07/" />
            <xs:element name="AddTask">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="task"
                                    nillable="true"
                                    type="q1:LocationTask" />
                        <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="user"
                                    nillable="true"
                                    type="q2:User" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="AddTaskResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0"
                                    name="AddTaskResult"
                                    type="xs:int" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetDistance">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q3="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="obj1"
                                    nillable="true"
                                    type="q3:Location" />
                        <xs:element xmlns:q4="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="obj2"
                                    nillable="true"
                                    type="q4:Location" />
                        <xs:element xmlns:q5="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="system"
                                    type="q5:Location.MeasurementSystem" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetDistanceResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0"
                                    name="GetDistanceResult"
                                    type="xs:double" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="FindNearTasks">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q6="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="center"
                                    nillable="true"
                                    type="q6:Location" />
                        <xs:element minOccurs="0"
                                    name="radius"
                                    type="xs:int" />
                        <xs:element xmlns:q7="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="system"
                                    type="q7:Location.MeasurementSystem" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="FindNearTasksResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q8="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="FindNearTasksResult"
                                    nillable="true"
                                    type="q8:ArrayOfLocationTask" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DeleteTask">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0"
                                    name="taskId"
                                    type="xs:int" />
                        <xs:element xmlns:q9="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="user"
                                    nillable="true"
                                    type="q9:User" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DeleteTaskResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0"
                                    name="DeleteTaskResult"
                                    type="xs:boolean" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="UpdateTask">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q10="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="task"
                                    nillable="true"
                                    type="q10:LocationTask" />
                        <xs:element xmlns:q11="http://schemas.datacontract.org/2004/07/"
                                    minOccurs="0"
                                    name="user"
                                    nillable="true"
                                    type="q11:User" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="UpdateTaskResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0"
                                    name="UpdateTaskResult"
                                    type="xs:boolean" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified"
                   elementFormDefault="qualified"
                   targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="anyType"
                        nillable="true"
                        type="xs:anyType" />
            <xs:element name="anyURI"
                        nillable="true"
                        type="xs:anyURI" />
            <xs:element name="base64Binary"
                        nillable="true"
                        type="xs:base64Binary" />
            <xs:element name="boolean"
                        nillable="true"
                        type="xs:boolean" />
            <xs:element name="byte"
                        nillable="true"
                        type="xs:byte" />
            <xs:element name="dateTime"
                        nillable="true"
                        type="xs:dateTime" />
            <xs:element name="decimal"
                        nillable="true"
                        type="xs:decimal" />
            <xs:element name="double"
                        nillable="true"
                        type="xs:double" />
            <xs:element name="float"
                        nillable="true"
                        type="xs:float" />
            <xs:element name="int"
                        nillable="true"
                        type="xs:int" />
            <xs:element name="long"
                        nillable="true"
                        type="xs:long" />
            <xs:element name="QName"
                        nillable="true"
                        type="xs:QName" />
            <xs:element name="short"
                        nillable="true"
                        type="xs:short" />
            <xs:element name="string"
                        nillable="true"
                        type="xs:string" />
            <xs:element name="unsignedByte"
                        nillable="true"
                        type="xs:unsignedByte" />
            <xs:element name="unsignedInt"
                        nillable="true"
                        type="xs:unsignedInt" />
            <xs:element name="unsignedLong"
                        nillable="true"
                        type="xs:unsignedLong" />
            <xs:element name="unsignedShort"
                        nillable="true"
                        type="xs:unsignedShort" />
            <xs:element name="char"
                        nillable="true"
                        type="tns:char" />
            <xs:simpleType name="char">
                <xs:restriction base="xs:int" />
            </xs:simpleType>
            <xs:element name="duration"
                        nillable="true"
                        type="tns:duration" />
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid"
                        nillable="true"
                        type="tns:guid" />
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType"
                          type="xs:QName" />
            <xs:attribute name="Id"
                          type="xs:ID" />
            <xs:attribute name="Ref"
                          type="xs:IDREF" />
        </xs:schema>
        <xs:schema elementFormDefault="qualified"
                   targetNamespace="http://schemas.datacontract.org/2004/07/"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:complexType name="LocationTask">
                <xs:sequence>
                    <xs:element minOccurs="0"
                                name="DatabaseId"
                                type="xs:int" />
                    <xs:element minOccurs="0"
                                name="Info"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Label"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="LastTimeModified"
                                type="xs:dateTime" />
                    <xs:element minOccurs="0"
                                name="Location"
                                nillable="true"
                                type="tns:Location" />
                    <xs:element minOccurs="0"
                                name="Name"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Status"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="UserEmail"
                                nillable="true"
                                type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="LocationTask"
                        nillable="true"
                        type="tns:LocationTask" />
            <xs:complexType name="Location">
                <xs:sequence>
                    <xs:element minOccurs="0"
                                name="Address"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Latitude"
                                type="xs:double" />
                    <xs:element minOccurs="0"
                                name="Longtitude"
                                type="xs:double" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="Location"
                        nillable="true"
                        type="tns:Location" />
            <xs:complexType name="User">
                <xs:sequence>
                    <xs:element minOccurs="0"
                                name="DatabaseId"
                                type="xs:int" />
                    <xs:element minOccurs="0"
                                name="Email"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Name"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Password"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="Surname"
                                nillable="true"
                                type="xs:string" />
                    <xs:element minOccurs="0"
                                name="UserLevel"
                                nillable="true"
                                type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="User"
                        nillable="true"
                        type="tns:User" />
            <xs:simpleType name="Location.MeasurementSystem">
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Imperial" />
                    <xs:enumeration value="Metric" />
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="Location.MeasurementSystem"
                        nillable="true"
                        type="tns:Location.MeasurementSystem" />
            <xs:complexType name="ArrayOfLocationTask">
                <xs:sequence>
                    <xs:element minOccurs="0"
                                maxOccurs="unbounded"
                                name="LocationTask"
                                nillable="true"
                                type="tns:LocationTask" />
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ArrayOfLocationTask"
                        nillable="true"
                        type="tns:ArrayOfLocationTask" />
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="ILocationBasedTasksService_AddTask_InputMessage">
        <wsdl:part name="parameters"
                   element="tns:AddTask" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_AddTask_OutputMessage">
        <wsdl:part name="parameters"
                   element="tns:AddTaskResponse" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_GetDistance_InputMessage">
        <wsdl:part name="parameters"
                   element="tns:GetDistance" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_GetDistance_OutputMessage">
        <wsdl:part name="parameters"
                   element="tns:GetDistanceResponse" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_FindNearTasks_InputMessage">
        <wsdl:part name="parameters"
                   element="tns:FindNearTasks" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_FindNearTasks_OutputMessage">
        <wsdl:part name="parameters"
                   element="tns:FindNearTasksResponse" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_DeleteTask_InputMessage">
        <wsdl:part name="parameters"
                   element="tns:DeleteTask" />
    </wsdl:message>
    <wsdl:message name="ILocationBasedTasksService_DeleteTask_OutputMessage">
        <wsdl:part name="parameters"
                   element="tns:DeleteTaskResponse" />
    </wsdl:message>
    <wsdl:portType name="ILocationBasedTasksService">
        <wsdl:operation name="AddTask">
            <wsdl:input message="tns:ILocationBasedTasksService_AddTask_InputMessage"
                        wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTask" />
            <wsdl:output message="tns:ILocationBasedTasksService_AddTask_OutputMessage"
                         wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTaskResponse" />
        </wsdl:operation>
        <wsdl:operation name="GetDistance">
            <wsdl:input message="tns:ILocationBasedTasksService_GetDistance_InputMessage"
                        wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistance" />
            <wsdl:output message="tns:ILocationBasedTasksService_GetDistance_OutputMessage"
                         wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistanceResponse" />
        </wsdl:operation>
        <wsdl:operation name="FindNearTasks">
            <wsdl:input message="tns:ILocationBasedTasksService_FindNearTasks_InputMessage"
                        wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasks" />
            <wsdl:output message="tns:ILocationBasedTasksService_FindNearTasks_OutputMessage"
                         wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasksResponse" />
        </wsdl:operation>
        <wsdl:operation name="DeleteTask">
            <wsdl:input message="tns:ILocationBasedTasksService_DeleteTask_InputMessage"
                        wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTask" />
            <wsdl:output message="tns:ILocationBasedTasksService_DeleteTask_OutputMessage"
                         wsaw:Action="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTaskResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_ILocationBasedTasksService"
                  type="tns:ILocationBasedTasksService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="AddTask">
            <soap:operation soapAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/AddTask"
                            style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetDistance">
            <soap:operation soapAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/GetDistance"
                            style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="FindNearTasks">
            <soap:operation soapAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/FindNearTasks"
                            style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="DeleteTask">
            <soap:operation soapAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/DeleteTask"
                            style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="UpdateTask">
            <soap:operation soapAction="http://Schema.Lukas.Somee.com/ILocationBasedTasksService/UpdateTask"
                            style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="LocationBasedTasksService">
        <wsdl:port name="BasicHttpBinding_ILocationBasedTasksService"
                   binding="tns:BasicHttpBinding_ILocationBasedTasksService">
            <soap:address location="http://lukas.somee.com/LocationBasedTasksService.svc" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
